apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        podAntiAffinity: ##podAntiAffinity =do not set all pods on same Node
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: my-app
                topologyKey: kubernetes.io/hostname #spread with node
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: my-app
          image: fasttapiacr69418.azurecr.io/my-app:latest
          ports:
            - containerPort: 8100
          #Readiness probe(check i  if its ready for traffic)
          readinessProbe:
              httpGet:
                path: /readyz
                port: 8100
              initialDelaySeconds: 5
              periodSeconds: 10
         #Livness probe(check if its alive the app)
          livenessProbe:
              httpGet:
                path: /healthz
                port: 8100
              initialDelaySeconds: 15
              periodSeconds: 20
       #Startup probe(in time for start (do not restart long time))
          startupProbe:
              httpGet:
                path: /healthz
                port: 8100
              failureThreshold: 30 #give time to application to run first #5min
              periodSeconds: 10

          #Resources(request+limits for scaling)
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

          #Secrets
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING2
              valueFrom:
                secretKeyRef:
                  name: azure-connection-secret
                  key: connectionString



