apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:

  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        podAntiAffinity: ##podAntiAffinity =do not set all pods on same Node
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: my-app
                topologyKey: kubernetes.io/hostname #spread with node

      containers:
        - name: my-app
          image: fasttapiacr69418.azurecr.io/my-app:latest
          ports:
            - containerPort: 8100
          #Readiness probe(check i  if its ready for traffic)
          readinessProbe:
              httpGet:
                path: /readyz
                port: 8100
              initialDelaySeconds: 5
              periodSeconds: 10
         #Livness probe(check if its alive the app)
          livenessProbe:
              httpGet:
                path: /healthz
                port: 8100
              initialDelaySeconds: 15
              periodSeconds: 20
       #Startup probe(in time for start (do not restart long time))
          startupProbe:
              httpGet:
                path: /healthz
                port: 8100
              failureThreshold: 30 #give time to application to run first #5min
              periodSeconds: 10

          #Resources(request+limits for scaling)
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

          #Secrets
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_HOST
          - name: AZURE_STORAGE_CONNECTION_STRING2
            valueFrom:
              secretKeyRef:
                name: azure-connection-secret
                key: connectionString


