# Kubernetes Deployment for your app. Pulls image from Azure Container Registry.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2 #Number of pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: davor.azurecr.io/my-app:latest # Acr Image path
          ports:
            - containerPort: 8000
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-connection-secret #Secret injected into container  with az cli
                  key: connectionString
