apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80 #users will open in this port and loadbalancer redirect to 8100(target port that is)
      targetPort: 8100
