name: Snyk Security Scan

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'  # once a week

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test.txt

      - name: Run Snyk to check for vulnerabilities
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --file=test.txt --package-manager=pip
  
